// Generates `coverage.md` and `dag.md` from `data/` and `items/`.
//
//   dart run tool/report.dart          # write both files
//   dart run tool/report.dart --check  # exit 1 if either file is stale

import 'dart:io';

import 'package:dart_cs1_inventory/dart_cs1_inventory.dart';
import 'package:path/path.dart' as p;

void main(List<String> args) {
  final check = args.contains('--check');
  final inv = Inventory.load();
  final outputs = {
    'coverage.md': _generated(renderCoverage(inv)),
    'dag.md': _generated(renderDag(inv)),
  };
  var stale = false;
  for (final MapEntry(key: name, value: content) in outputs.entries) {
    final file = File(p.join(inv.root, name));
    if (check) {
      final current = file.existsSync() ? file.readAsStringSync() : null;
      if (current != content) {
        stderr.writeln('$name is stale; run `dart run tool/report.dart`');
        stale = true;
      }
    } else {
      file.writeAsStringSync(content);
      stdout.writeln('wrote $name');
    }
  }
  if (stale) exitCode = 1;
}

/// Generated tables and wrapped prose are not stable under prettier, so the
/// whole body is range-ignored; `.prettierrc.json` stays canonical.
String _generated(String body) =>
    '<!-- prettier-ignore-start -->\n$body<!-- prettier-ignore-end -->\n';

// ---------------------------------------------------------------- coverage

String renderCoverage(Inventory inv) {
  final b = StringBuffer();
  final itemsByArea = <String, List<Item>>{};
  for (final item in inv.items) {
    for (final a in item.specAreas) {
      itemsByArea.putIfAbsent(a, () => []).add(item);
    }
  }

  b.writeln('''
# Dart spec coverage of an FCS1-shaped concept inventory

<!-- Generated by `dart run tool/report.dart`; edit `data/*.yaml` instead. -->

## Provenance and constraints

- **FCS1** (Tew & Guzdial, SIGCSE 2011) and **SCS1** (Parker, Guzdial &
  Engleman, ICER 2016) are secure instruments. SCS1 is administered only
  through the LASSO platform, whose terms forbid changing question order,
  wording or answer options; FCS1 is by request from the authors. A Dart
  port is itself a modification, so **no FCS1/SCS1 item text was obtained or
  used**. Everything under `items/` is original, written to the published
  ten-concept × three-question-type structure.
- Spec references are *section titles* from `dart-lang/language`
  `specification/dartLangSpec.tex` (numbers change between editions) or
  paths under `accepted/<version>/` for features specified outside the main
  text.
- Coverage below is computed from `spec_areas:` on each item, not estimated.

## Item matrix

${_matrix(inv)}

## Spec areas exercised

Areas in FCS1 scope, with the items that touch them. ⚠️ marks an in-scope
area no item exercises yet.

| Area | Spec reference | Items |
| --- | --- | --- |''');
  for (final a in inv.specAreas.where((a) => a.cs1Scope)) {
    final items = itemsByArea[a.id] ?? const [];
    final flag = items.isEmpty ? '⚠️ ' : '';
    b.writeln(
      '| $flag`${a.id}` — ${_md(a.title)} | ${_md(a.reference)} | '
      '${items.isEmpty ? '—' : items.map((i) => '`${i.id}`').join(', ')} |',
    );
  }

  final leaked = inv.specAreas
      .where((a) => !a.cs1Scope && (itemsByArea[a.id]?.isNotEmpty ?? false))
      .toList();
  b.writeln('''

## Areas outside CS1 scope that items still touch

${leaked.isEmpty ? '_None._' : ''}''');
  for (final a in leaked) {
    b.writeln(
      '- `${a.id}` — ${_md(a.title)}: '
      '${itemsByArea[a.id]!.map((i) => '`${i.id}`').join(', ')}',
    );
  }

  b.writeln('''

## Gaps: what a Dart-specific inventory would need

Spec areas with no FCS1 concept behind them. Grouped; each is a candidate node
for the Dart-teaching DAG once the CS1 core is secure.
''');
  final groups = <String, List<SpecArea>>{};
  for (final a in inv.specAreas.where((a) => !a.cs1Scope)) {
    if (itemsByArea[a.id]?.isNotEmpty ?? false) continue;
    groups.putIfAbsent(a.group, () => []).add(a);
  }
  for (final MapEntry(key: group, value: areas) in groups.entries) {
    b
      ..writeln('### $group\n')
      ..writeln('| Area | Spec reference | Note |')
      ..writeln('| --- | --- | --- |');
    for (final a in areas) {
      b.writeln(
        '| `${a.id}` — ${_md(a.title)} | ${_md(a.reference)} | '
        '${a.note.isEmpty ? '' : _md(a.note)} |',
      );
    }
    b.writeln();
  }

  b.writeln('''
## Concepts that do not translate cleanly from pseudocode
''');
  for (final t in inv.translationIssues) {
    b
      ..writeln('### ${t.title}\n')
      ..writeln('Concepts: ${t.concepts.map((c) => '`$c`').join(', ')}\n')
      ..writeln('${t.problem.trim()}\n')
      ..writeln('**Decision:** ${t.decision.trim()}\n');
  }

  b.writeln('''
## Drill candidates

Concepts flagged for drill-style practice (token discrimination,
special-character typing, trace tables), from `data/concepts.yaml`.
''');
  for (final c in inv.concepts) {
    if (c.drills.isEmpty) continue;
    b.writeln('- **${c.title}**');
    for (final d in c.drills) {
      b.writeln('  - $d');
    }
  }

  b.writeln('''

## Appendix: item → spec area mapping

| Item | Type | Spec areas |
| --- | --- | --- |''');
  for (final i in inv.items) {
    b.writeln(
      '| `${i.id}` | ${i.type.name} | '
      '${i.specAreas.map((a) => '`$a`').join(', ')} |',
    );
  }
  return b.toString();
}

String _matrix(Inventory inv) {
  final b = StringBuffer()
    ..writeln('| Concept | FCS1 name | definitional | tracing | completion |')
    ..writeln('| --- | --- | ---: | ---: | ---: |');
  var total = 0;
  for (final c in inv.concepts) {
    final counts = [
      for (final t in ItemType.values) inv.itemsFor(c.id, t).length,
    ];
    total += counts.fold(0, (a, b) => a + b);
    b.writeln('| `${c.id}` | ${c.fcs1Name} | ${counts.join(' | ')} |');
  }
  b.write('| **total** | | | | **$total** |');
  return b.toString();
}

// --------------------------------------------------------------------- dag

String renderDag(Inventory inv) {
  final byId = {for (final n in inv.dag) n.id: n};
  final depth = <String, int>{};
  int depthOf(String id) => depth[id] ??= switch (byId[id]!.prerequisites) {
    [] => 0,
    final pres => 1 + pres.map(depthOf).reduce((a, b) => a > b ? a : b),
  };
  for (final n in inv.dag) {
    depthOf(n.id);
  }
  final maxDepth = depth.values.reduce((a, b) => a > b ? a : b);

  final b = StringBuffer('''
# Proposed prerequisite DAG for the CS1-through-Dart concepts

<!-- Generated by `dart run tool/report.dart`; edit `data/dag.yaml` instead. -->

A knowledge-space-style map: a node is available once every prerequisite has
been demonstrated (e.g. by answering its items). Nodes are finer than the ten
FCS1 concepts because the concepts are not atomic. Edges are **proposals** from
item analysis, not measured from student data; see the open questions at the
end.

## Graph

```mermaid
flowchart TD
''');
  for (final n in inv.dag) {
    b.writeln('  ${n.id}["${_mermaid(n.title)}"]');
  }
  for (final n in inv.dag) {
    for (final pre in n.prerequisites) {
      b.writeln('  $pre --> ${n.id}');
    }
  }
  b
    ..writeln('```\n')
    ..writeln('## Levels (longest prerequisite chain)\n');
  for (var d = 0; d <= maxDepth; d++) {
    final ids = inv.dag.where((n) => depth[n.id] == d).map((n) => n.id);
    b.writeln('- **Level $d**: ${ids.map((i) => '`$i`').join(', ')}');
  }

  b.writeln('''

## Nodes

| Node | FCS1 concept | Prerequisites | Items | Rationale |
| --- | --- | --- | ---: | --- |''');
  for (final n in inv.dag) {
    final items = inv.items.where((i) => i.dagNode == n.id).length;
    final concept = n.concept == null ? '—' : '`${n.concept}`';
    final pres = n.prerequisites.isEmpty
        ? '—'
        : n.prerequisites.map((x) => '`$x`').join(', ');
    b.writeln(
      '| `${n.id}` — ${_md(n.title)} | $concept | $pres | '
      '${items == 0 ? '⚠️ 0' : '$items'} | ${_md(n.rationale.trim())} |',
    );
  }

  b.writeln('''

## Open questions

- Every item carries a `dag_node:`; ⚠️ marks nodes with no evidence items
  yet (they can only be "passed" by their successors' items).
- `definite_loops` and `indefinite_loops` are siblings here. Curricula
  disagree; if `for-in` is taught first the `while` node could depend on it.
- `recursion` depends on `return_values` and scope but *not* on loops. That
  is a deliberate stance (recursion is not "a kind of loop") and should be
  validated against item data.
- `aliasing_references` is the first reference-semantics node and feeds three
  later nodes; if it proves too hard before functions, `list_parameters`
  could be where it is first introduced instead.
- The gap areas in `coverage.md` are not in the graph yet. Likely first
  additions: `types.nullable` (after `variables_assignment`), `expressions.maps`
  (after `lists_indexing`), `functions.optional_formals` (after
  `function_calls_and_params`), `patterns` (after `selection` + `records`).
''');
  return b.toString();
}

String _md(String s) => s.replaceAll('|', r'\|').replaceAll('\n', ' ');

String _mermaid(String s) => s.replaceAll('"', '#quot;').replaceAll('`', '');
